site_name: Avalonia TroubleShooting Guidebook
site_url: https://metaone01.github.io/avalonia-troubleshooting-guidebook
repo_url: https://github.com/metaone01/avalonia-troubleshooting-guidebook

docs_dir: docs/

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: '#'
      toc_depth: 3

extra_javascript:
  - assets/tags.js

extra_css:
  - assets/extra.css
  - assets/tags.css

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.expand
    - navigation.tracking
    - footer.social
    - footer.icons
    - palette.toggle
    - palette.icon
    - announcement.bar

plugins:
  - search
  - tags:
      tags_allowed:
        - Avalonia
        - Xaml
        - Style
        - Event
        - Binding
        - Code Behind
        - ViewModel
        - Data
        - Data Validation
        # Multi-OS
        - Windows
        - Linux
        - MacOS
        - Android
        - Web
        # Special
        - Outdated
        - WIP
        - Experimental
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          site_name: Avalonia TroubleShooting Guidebook
          build: true

        - locale: zh
          default: true
          name: 简体中文
          site_name: Avalonia 故障排除指南
          build: true
          nav_translations:
            Avalonia: Avalonia相关
            Style: 样式
            Binding: 绑定
            Event: 事件
            Multi OS: 跨平台

  - git-revision-date-localized:
      fallback_to_build_date: true
      type: timeago
