name: New Solution
description: Share a new troubleshooting experience.
labels: ["new page", "solution"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the problem
      description: Also tell us, what did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: To Reproduce
      description: How can this error be reproduced?

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Your solution. We also hope you provide the failed tests to better understand your troubleshooting approach.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Your OS's version, architecture, and Avalonia's version.
      placeholder: e.g. Windows 11 24H2 , amd64, Avalonia 11.3.4

  - type: dropdown
    id: all-platform
    attributes:
      label: Does the problem happen on all platforms?
      options:
        - label: Yes
        - label: No
        - label: I don't know
    validations:
      required: true

  - type: dropdown
    id: relevance
    attributes:
      label: Is this directly relevant to Avalonia?
      options:
        - label: Yes
          description: This is an Avalonia problem.
        - label: No
          description: This is the other codes' problem in my Avalonia project.
        - label: Affected
          description: Some of the other codes affect Avalonia.
        - label: Interfere
          description: Avalonia affects other codes.
        - label: Unexpected
          description: The behavior is unexpected, but the relationship between Avalonia and other code is uncertain.
        - label: Conflict
          description: Affected and Disturb.
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
