name: Report a Document Outdated
description: Some content of the page is outdated.
labels: ["document", "outdated-report"]
body:
  - type: input
    id: page-url
    attributes:
      label: Page URL
      description: The URL of the page which is outdated.
    validations:
      required: true

  - type: textarea
    id: outdated-content
    attributes:
      label: Outdated Content
      description: Outdated content or its line range.
    validations:
      required: true

  - type: input
    id: latest-source
    attributes:
      label: Latest Source URL
      description: What is the latest source of this content?
    validations:
      required: true

  - type: textarea
    id: correction
    attributes:
      label: New Content
      description: What's the latest information? How can we update this?

  - type: checkboxes
    id: pr-willingness
    label: Help to Correct
    attributes:
      options:
        - label: I'm willing to create a pull request to update its Chinese version.
        - label: I'm willing to create a pull request to update its English version.

  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      description: Add any other context about the report here.
