name: Report a Document Error
description: Some content in the page is incorrect.
labels: ["document", "error-report"]
body:
  - type: input
    id: page-url
    attributes:
      label: Page URL
      description: The URL of the page where you found the error.
    validations:
      required: true

  - type: textarea
    id: wrong
    attributes:
      label: Wrong Content
      description: Error content or its line range
    validations:
      required: true

  - type: textarea
    id: correction
    attributes:
      label: Correction
      description: How can we correct this error?

  - type: checkboxes
    id: pr-willingness
    attributes:
      options:
        - label: I'm willing to create a pull request to correct its Chinese version.
        - label: I'm willing to create a pull request to correct its English version.

  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      description: Add any other context about the report here.
